title: Mộc cảm sinh
description: sống thật với mình, nhẹ bước giữa đời, vững tin vào những điều đang đến
author: muziii
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag